version: "3"

vars:
  IMAGE_WEBAPP: ghcr.io/celine-eu/celine-webapp
  IMAGE_ASSISTANT: ghcr.io/celine-eu/celine-assistant

tasks:
  # Development
  dev:webapp:
    desc: Run webapp in development mode
    cmds:
      - pnpm dev:webapp

  dev:assistant:
    desc: Run assistant in development mode
    cmds:
      - pnpm dev:assistant

  # Build
  build:
    desc: Build all apps
    cmds:
      - pnpm build

  build:webapp:
    desc: Build webapp
    cmds:
      - pnpm build:webapp

  build:assistant:
    desc: Build assistant
    cmds:
      - pnpm build:assistant

  # Release - auto version based on conventional commits
  release:webapp:
    desc: Release webapp (auto version from commits, generates changelog)
    dir: apps/webapp
    cmds:
      - npx release-it --ci {{.CLI_ARGS}}

  release:assistant:
    desc: Release assistant (auto version from commits, generates changelog)
    dir: apps/assistant
    cmds:
      - npx release-it --ci {{.CLI_ARGS}}

  # Dry run to preview release
  release:webapp:dry:
    desc: Preview webapp release (dry run)
    dir: apps/webapp
    cmds:
      - npx release-it --dry-run

  release:assistant:dry:
    desc: Preview assistant release (dry run)
    dir: apps/assistant
    cmds:
      - npx release-it --dry-run

  # Docker builds
  docker:webapp:
    desc: Build webapp Docker image
    cmds:
      - docker build -f apps/webapp/Dockerfile -t {{.IMAGE_WEBAPP}}:dev .

  docker:assistant:
    desc: Build assistant Docker image
    cmds:
      - docker build -f apps/assistant/Dockerfile -t {{.IMAGE_ASSISTANT}}:dev .

  docker:all:
    desc: Build all Docker images
    cmds:
      - task: docker:webapp
      - task: docker:assistant
