import { expect, test } from '@playwright/test';
import { openSignedIn } from './sign-in';

/**
 * The assistant tells people they are talking to an AI (EU AI Act art. 50) before they write,
 * in the language the app picked, with a link to the privacy policy.
 */
const ASSISTANT_URL = process.env.E2E_ASSISTANT_URL ?? 'http://assistant.celine.localhost';

const NOTICE: Record<string, { browser: string; text: RegExp }> = {
  en: { browser: 'en-GB', text: /Answers are generated by AI through OpenAI and can be wrong/ },
  it: { browser: 'it-IT', text: /Le risposte sono generate dall'IA tramite OpenAI/ },
  es: { browser: 'es-ES', text: /Las respuestas las genera una IA a través de OpenAI/ },
};

for (const [lang, { browser, text }] of Object.entries(NOTICE)) {
  test.describe(`assistant in ${lang}`, () => {
    test.use({ locale: browser });

    test('shows the AI notice beside the composer, linking the privacy policy', async ({ page }) => {
      await openSignedIn(page, ASSISTANT_URL);

      const notice = page.locator('.ai-notice');
      await expect(notice).toBeVisible();
      await expect(notice).toContainText(text);

      const link = notice.getByRole('link');
      await expect(link).toHaveAttribute('href', /.+/);
      await expect(link).toHaveAttribute('target', '_blank');
      await expect(link).toHaveAttribute('rel', /noopener/);
    });
  });
}
